"""Справочник man-страниц для terminal-команд."""

MAN_PAGES: dict[str, str] = {
    "help": "help — список команд по категориям.\nПример: help",
    "about": "about — информация о владельце хаба.\nВеб: /about",
    "contact": "contact — каналы связи.\ncontact <key> — открыть ссылку.\nВеб: /contact",
    "projects": "projects — список проектов портфолио.\nПример: projects",
    "project": "project <slug> — карточка проекта.\nПример: project personal-me",
    "services": "services — список внешних интеграций.\nПример: services",
    "go": "go <service> — открыть интеграцию в новой вкладке.\nПример: go grafana",
    "login": "login — открыть форму входа (пароль не попадает в историю).",
    "logout": "logout — выход из текущей сессии.",
    "register": "register — форма регистрации (если включена).",
    "profile": "profile — профиль и смена пароля.\nВеб: /profile",
    "whoami": "whoami — текущий пользователь или guest.",
    "pwd": "pwd — текущий каталог (~/personal_me).",
    "session": "session — сводка сессии терминала.",
    "theme": "theme <auto|green|amber|blue> — цветовая тема.",
    "fx": "fx — эффекты UI.\nfx preset <minimal|retro|hacker|off>\nfx toggle <scanlines|glow|vignette|grain>",
    "matrix": "matrix — easter egg.",
    "sudo": "sudo — easter egg.",
    "vim": "vim — easter egg.",
    "lang": "lang <ru|en> — язык интерфейса.",
    "alias": "alias <name>=<command> — пользовательский алиас.\nПример: alias ll=projects",
    "clear": "clear — очистить экран терминала.",
    "status": "status — health API, БД и SMTP.",
    "man": "man <command> — справка по команде.\nПример: man go",
    "password": "password <текущий> <новый> — смена пароля (нужен login).",
    "reset-request": "reset-request <логин|email> — запрос сброса пароля.",
    "reset-password": "reset-password <token> <новый> — подтверждение сброса.",
    "integrations": "integrations — все интеграции (только admin).",
}
